---
folders:
  kavikaran:
    datpath: /data/patients/
    path2itksnap: /Applications/ITK-SNAP.app/Contents/MacOS/ITK-SNAP
    testdata: /data/patients/4701P
  david:
    datpath: /data/patients/
    path2itksnap: /usr/lib/snap-3.6.0
    testdata: data/patients/4701P
