---
folders:
  kavikaran:
    datpath: data/patients/
    path2itksnap: /Applications/ITK-SNAP.app/Contents/MacOS/ITK-SNAP
    testdata: /data/test/3571P/
    standarddata: /data/standard/
    outputpath: /data/output/
  david:
    datpath: data/patients/
    path2itksnap: /usr/lib/snap-3.6.0
    testdata: /data/patients/4701P
    outputpath: data/output/4839P
    standarddata: /data/template/
  dplab:
    datpath: data/
    path2itksnap: /usr/lib/snap-3.6.0
    testdata: /data/4701P
    outputpath: data/4701P
    standarddata: /data/template/

preprocess:
  ANTsN4:
    bspline-fitting: 200
    convergence:
    - 50
    - 50
    - 50
    - 50
    denoise: 'no'
    prefix: bc_
    shrink-factor: 4
    threshold: 1.0e-07
  Registration:
    prefix: reg_
    metric: mattes
    registration_method: SyNRA
    resample_spacing: '0.7'

malf:
  atlas: 'OASIS' #'hamersN30R83'
  template: 'T_template0.nii.gz'